runtime: python312
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  SENDGRID_API_KEY: 'was to chnage HIDDEN_FOR_SECURITY API KEY'

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
