runtime: python312
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  SENDGRID_API_KEY: 'projects/trafxcloud/secrets/sendgrid-api-key/versions/latest'

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
